# Використовуємо базовий образ Node.js
FROM node:14

# Встановлюємо робочу директорію
WORKDIR /app

# Копіюємо package.json і package-lock.json
COPY package*.json ./

# Встановлюємо залежності
RUN npm install

# Копіюємо всі файли додатку
COPY . .

# Відкриваємо порт
EXPOSE 3000

# Запускаємо додаток
CMD ["node", "server.js"]
