version: '2.27'

services:
  web:
    image: maksimr17/todo-app
    build:
      context: .
      dockerfile: Dockerfile.txt
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
